name: Deploy

on:
  push:
    branches:
      - main
      - fixdeploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Install deps
        run: nix develop --command bash -c 'pnpm i'

      - name: Build content
        run: nix develop --command bash -c 'pnpm build'

      - name: show content
        run: ls dist/

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact
      #     path: dist/**/*

      # - uses: actions/download-artifact@v4
      #   with:
      #     name: my-artifact
      #     path: artifacts

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.4
        # if: github.ref == 'refs/heads/main'
        if: github.ref == 'refs/heads/fixdeploy'
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "dist/*"
          target: ${{ secrets.TARGET }}
          strip_components: 1
