name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Install deps
        run: nix develop --command bash -c 'pnpm i'

      - name: Build content
        run: nix develop --command bash -c 'pnpm build'

      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        if: github.ref == 'refs/heads/main'
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "dist/*"
          target: ${{ secrets.TARGET }}
          strip_components: 1
